import { db } from '@/db';
import { exercises } from '@/db/schema';

async function main() {
    // 20 Exercises accurately graded by Level (1 to 4) using user images
    const sampleExercises = [
        // ─── Level 1: Beginner Foundation ───
        {
            name: 'Incline Push-ups',
            description: 'Beginner push-up variation using an elevated surface. Reduces body weight resistance, perfect for building chest, shoulder, and tricep foundation.',
            imageUrl: '/images/Incline push ups.png',
            type: 'bodyweight',
            bodyParts: ['Chest', 'Triceps', 'Shoulders'],
            tags: ['calisthenics', 'beginner', 'upper body', 'strength'],
            level: '1',
            split: 'push',
            repGoal: 12,
        },
        {
            name: 'Bar Hang',
            description: 'Hang from a pull-up bar with arms fully extended. Essential for developing grip strength, scapular control, decompression, and shoulder health.',
            imageUrl: '/images/Bar Hang.png',
            type: 'timer',
            bodyParts: ['Forearms', 'Lats', 'Shoulders'],
            tags: ['calisthenics', 'grip strength', 'decompression', 'recovery'],
            level: '1',
            split: 'pull',
            repGoal: 30,
        },
        {
            name: 'Bodyweight Squats',
            description: 'Foundational lower body bodyweight exercise. Lower hips until thighs are parallel to the floor. Builds quad, glute strength, and hip mobility.',
            imageUrl: '/images/Bodyweight Squats.png',
            type: 'bodyweight',
            bodyParts: ['Quads', 'Glutes', 'Hamstrings'],
            tags: ['calisthenics', 'lower body', 'foundation', 'mobility'],
            level: '1',
            split: 'legs',
            repGoal: 15,
        },
        {
            name: 'Glute Bridges',
            description: 'Lie on your back with knees bent and lift your hips toward the ceiling. Activates the glutes, hamstrings, and strengthens the lower back.',
            imageUrl: '/images/Glute Bridges.png',
            type: 'bodyweight',
            bodyParts: ['Glutes', 'Hamstrings', 'Lower Back'],
            tags: ['posterior chain', 'activation', 'mobility', 'strength'],
            level: '1',
            split: 'legs',
            repGoal: 15,
        },
        {
            name: 'Plank Hold',
            description: 'Isometric core exercise maintaining a straight line from head to heels. Develops deep abdominal stability, endurance, and proper posture.',
            imageUrl: '/images/Plank Hold.png',
            type: 'timer',
            bodyParts: ['Core / Abs', 'Obliques', 'Shoulders'],
            tags: ['isometric', 'core stability', 'endurance'],
            level: '1',
            split: 'core',
            repGoal: 45,
        },
        {
            name: 'Mountain Climbers',
            description: 'Dynamic plank position running motion alternating knees to chest. Great for cardiovascular conditioning, core stamina, and agility.',
            imageUrl: '/images/Mountain Climbers.png',
            type: 'standard',
            bodyParts: ['Core / Abs', 'Shoulders', 'Quads'],
            tags: ['cardio', 'hiit', 'dynamic', 'endurance'],
            level: '1',
            split: 'core',
            repGoal: 20,
        },

        // ─── Level 2: Novice Strength & Control ───
        {
            name: 'Push Ups',
            description: 'Standard floor push-up. Lower chest until nearly touching the floor and press back up with a rigid core. Classic upper body compound movement.',
            imageUrl: '/images/Push Ups.png',
            type: 'bodyweight',
            bodyParts: ['Chest', 'Triceps', 'Shoulders', 'Core / Abs'],
            tags: ['calisthenics', 'upper body', 'strength', 'compound'],
            level: '2',
            split: 'push',
            repGoal: 15,
        },
        {
            name: 'Walking Lunges',
            description: 'Dynamic walking lunges stepping forward. Builds unilateral leg strength, quad control, glute stability, and hip balance.',
            imageUrl: '/images/Walking Lunges.png',
            type: 'bodyweight',
            bodyParts: ['Quads', 'Glutes', 'Hamstrings', 'Calves'],
            tags: ['calisthenics', 'unilateral', 'lower body', 'mobility'],
            level: '2',
            split: 'legs',
            repGoal: 16,
        },
        {
            name: 'Chair Dips',
            description: 'Bench or chair dips with hands placed behind hips. Focuses on triceps extension, anterior deltoids, and pushing stamina.',
            imageUrl: '/images/Chair Dips.png',
            type: 'bodyweight',
            bodyParts: ['Triceps', 'Chest', 'Shoulders'],
            tags: ['calisthenics', 'arms', 'pressing', 'triceps'],
            level: '2',
            split: 'push',
            repGoal: 12,
        },
        {
            name: 'Bicep Curls',
            description: 'Classic arm curl exercise focusing on isolated bicep peak contraction, grip stability, and forearm control.',
            imageUrl: '/images/Bicep Curls.png',
            type: 'weighted',
            bodyParts: ['Biceps', 'Forearms'],
            tags: ['isolation', 'arms', 'hypertrophy', 'strength'],
            level: '2',
            split: 'pull',
            repGoal: 12,
        },
        {
            name: 'Single-Leg Glute Bridges',
            description: 'Unilateral glute bridge performed with one leg elevated. Corrects side-to-side muscle imbalances and strengthens hamstrings and glutes.',
            imageUrl: '/images/Single-Leg Glute Bridges.png',
            type: 'bodyweight',
            bodyParts: ['Glutes', 'Hamstrings', 'Core / Abs'],
            tags: ['unilateral', 'posterior chain', 'stability'],
            level: '2',
            split: 'legs',
            repGoal: 10,
        },

        // ─── Level 3: Intermediate Mastery ───
        {
            name: 'Chin-ups',
            description: 'Pulling exercise with supinated (underhand) grip. Heavy bicep and lat engagement through a full range of motion from dead hang to chin above bar.',
            imageUrl: '/images/Chin-ups.png',
            type: 'bodyweight',
            bodyParts: ['Biceps', 'Lats', 'Upper Back'],
            tags: ['calisthenics', 'pulling', 'biceps', 'compound'],
            level: '3',
            split: 'pull',
            repGoal: 8,
        },
        {
            name: 'Pull Ups',
            description: 'Overhand grip pull-up hanging from a dead hang to chin over the bar. The gold standard for back width, lats, and pulling power.',
            imageUrl: '/images/Pull Ups.png',
            type: 'bodyweight',
            bodyParts: ['Lats', 'Upper Back', 'Biceps', 'Forearms'],
            tags: ['calisthenics', 'back', 'compound', 'strength'],
            level: '3',
            split: 'pull',
            repGoal: 8,
        },
        {
            name: 'Dips',
            description: 'Parallel bar dips lowering until elbows reach 90 degrees. Exceptional builder for lower chest mass and tricep lockout power.',
            imageUrl: '/images/Dips.png',
            type: 'bodyweight',
            bodyParts: ['Chest', 'Triceps', 'Shoulders'],
            tags: ['calisthenics', 'pressing', 'compound', 'strength'],
            level: '3',
            split: 'push',
            repGoal: 10,
        },
        {
            name: 'Jump Squats',
            description: 'Explosive bodyweight squat launching vertically into a jump. Builds explosive leg power, fast-twitch muscle fibers, and stamina.',
            imageUrl: '/images/Jump Squats.png',
            type: 'bodyweight',
            bodyParts: ['Quads', 'Glutes', 'Calves'],
            tags: ['plyometrics', 'explosive', 'power', 'hiit'],
            level: '3',
            split: 'legs',
            repGoal: 12,
        },
        {
            name: 'Pike Push-ups',
            description: 'Push-up with hips elevated high in an inverted V-shape. Shifts resistance directly onto the deltoids, preparing for handstands.',
            imageUrl: '/images/Pike Push-ups.png',
            type: 'bodyweight',
            bodyParts: ['Shoulders', 'Triceps', 'Upper Back'],
            tags: ['calisthenics', 'overhead press', 'handstand prep', 'strength'],
            level: '3',
            split: 'push',
            repGoal: 10,
        },
        {
            name: 'Bulgarian Split Squats',
            description: 'Rear foot elevated split squat. Unilateral powerhouse exercise for quad development, deep glute recruitment, and hip flexor stretch.',
            imageUrl: '/images/Bulgarian Split Squats.png',
            type: 'bodyweight',
            bodyParts: ['Quads', 'Glutes', 'Hamstrings'],
            tags: ['unilateral', 'lower body', 'strength', 'balance'],
            level: '3',
            split: 'legs',
            repGoal: 10,
        },

        // ─── Level 4: Advanced Calisthenics ───
        {
            name: 'Archer Push-ups',
            description: 'Wide grip push-up shifting bodyweight primarily to one arm while the other stays straight. Key milestone towards the one-arm push-up.',
            imageUrl: '/images/Archer Push-ups.png',
            type: 'bodyweight',
            bodyParts: ['Chest', 'Triceps', 'Shoulders', 'Core / Abs'],
            tags: ['calisthenics', 'advanced', 'one-arm prep', 'strength'],
            level: '4',
            split: 'push',
            repGoal: 8,
        },
        {
            name: 'Clapping Push-ups',
            description: 'Explosive plyometric push-up pushing off the floor with enough force to clap hands in mid-air before landing smoothly with bent elbows.',
            imageUrl: '/images/Clapping Push-ups.png',
            type: 'bodyweight',
            bodyParts: ['Chest', 'Triceps', 'Shoulders'],
            tags: ['plyometrics', 'explosive', 'power', 'advanced'],
            level: '4',
            split: 'push',
            repGoal: 8,
        },
        {
            name: 'Pseudo Planche Push-ups',
            description: 'Push-up with hands placed closer to the hips and heavy forward shoulder lean. High shoulder leverage mimicking the planche.',
            imageUrl: '/images/Pseudo Planche Push-ups.png',
            type: 'bodyweight',
            bodyParts: ['Shoulders', 'Chest', 'Core / Abs', 'Forearms'],
            tags: ['calisthenics', 'planche', 'advanced', 'shoulder power'],
            level: '4',
            split: 'push',
            repGoal: 8,
        },
    ];

    // Clear existing exercises and re-seed cleanly
    await db.delete(exercises);

    const mapped = sampleExercises.map((ex) => ({
        userId: 'user_1',
        createdBy: 'user_1',
        name: ex.name,
        description: ex.description,
        imageUrl: ex.imageUrl,
        type: ex.type,
        bodyParts: ex.bodyParts,
        tags: ex.tags,
        level: ex.level,
        split: ex.split,
        repGoal: ex.repGoal,
        createdAt: new Date(),
    }));

    await db.insert(exercises).values(mapped);
    
    console.log(`✅ Successfully seeded ${mapped.length} level-graded exercises with images!`);
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});